"""Declare, Type and Const: compile rules and runtime raises.

    python gen_dtc.py CASES.json
"""

import json
import sys

HEAD = "Option Explicit\r\n"


def std(label: str, decl: str, body: str, extra: str = "") -> dict:
    body = "".join("    " + ln + "\r\n" for ln in body.split("\n")) if body else ""
    src = HEAD + decl + "Public Function Main() As Variant\r\n" + body + "End Function\r\n" + extra
    return {"label": label, "run": "Module1.Main",
            "modules": [{"name": "Module1", "type": "standard", "source": src}]}


def two(label: str, decl1: str, body: str, src2: str) -> dict:
    case = std(label, decl1, body)
    case["modules"].append({"name": "Module2", "type": "standard", "source": HEAD + src2})
    return case


TICK = 'Private Declare PtrSafe Function GetTickCount Lib "kernel32" () As Long\r\n'
SLEEP = 'Private Declare PtrSafe Sub Sleep Lib "kernel32" (ByVal ms As Long)\r\n'
T = "Private Type T\r\n    a As Long\r\n    i As Integer\r\n    s As String\r\n    d() As Long\r\n    f(0 To 2) As Long\r\n    o As Collection\r\n    dt As Date\r\n    b As Byte\r\nEnd Type\r\n"
U = "Private Type U\r\n    a As Long\r\n    i As Integer\r\n    s As String\r\n    d() As Long\r\n    f(0 To 2) As Long\r\n    o As Collection\r\n    dt As Date\r\n    b As Byte\r\nEnd Type\r\n"
TS = "Private Sub TakeV(ByVal v As Variant)\r\nEnd Sub\r\nPrivate Sub TakeT(x As T)\r\nEnd Sub\r\nPrivate Function MakeT() As T\r\n    MakeT.a = 1\r\nEnd Function\r\n"

CASES = [
    # ---- Declare ----
    std("dec-ok", TICK, "Main = GetTickCount() > 0"),
    std("dec-missing-dll", 'Private Declare PtrSafe Function Nope Lib "nosuchlib_xyz" () As Long\r\n', "Main = Nope()"),
    std("dec-missing-entry", 'Private Declare PtrSafe Function Nope Lib "kernel32" Alias "NoSuchEntryXyz" () As Long\r\n', "Main = Nope()"),
    std("dec-missing-dll-uncalled", 'Private Declare PtrSafe Function Nope Lib "nosuchlib_xyz" () As Long\r\n', "Main = 1"),
    std("dec-wrong-argc-more", TICK, "Main = GetTickCount(1)"),
    std("dec-wrong-argc-less", SLEEP, "Sleep\nMain = 1"),
    std("dec-sub-as-func", SLEEP, "Main = Sleep(1)"),
    std("dec-assign-to", TICK, "GetTickCount = 5\nMain = 1"),
    std("dec-sub-with-type", 'Private Declare PtrSafe Sub Sleep Lib "kernel32" (ByVal ms As Long) As Long\r\n', "Main = 1"),
    std("dec-optional", 'Private Declare PtrSafe Sub Sleep Lib "kernel32" (Optional ByVal ms As Long)\r\n', "Sleep\nMain = 1"),
    std("dec-paramarray", 'Private Declare PtrSafe Sub Sleep Lib "kernel32" (ParamArray ms() As Variant)\r\n', "Main = 1"),
    std("dec-array-param", 'Private Declare PtrSafe Sub Sleep Lib "kernel32" (ms() As Long)\r\n', "Main = 1"),
    std("dec-udt-byval", T + 'Private Declare PtrSafe Sub Sleep Lib "kernel32" (ByVal ms As T)\r\n', "Main = 1"),
    std("dec-udt-byref", T + 'Private Declare PtrSafe Sub Sleep Lib "kernel32" (ms As T)\r\n', "Main = 1"),
    std("dec-returns-udt", T + 'Private Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As T\r\n', "Main = 1"),
    std("dec-returns-string", 'Private Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As String\r\n', "Main = 1"),
    std("dec-returns-object", 'Private Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As Collection\r\n', "Main = 1"),
    std("dec-returns-fixedstr", 'Private Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As String * 4\r\n', "Main = 1"),
    std("dec-param-fixedstr", 'Private Declare PtrSafe Sub F Lib "kernel32" Alias "Sleep" (ByVal s As String * 4)\r\n', "Main = 1"),
    std("dec-param-object-byval", 'Private Declare PtrSafe Sub F Lib "kernel32" Alias "Sleep" (ByVal c As Collection)\r\n', "Main = 1"),
    std("dec-cdecl", 'Private Declare PtrSafe Function F CDecl Lib "kernel32" Alias "GetTickCount" () As Long\r\n', "Main = F() > 0"),
    std("dec-empty-alias", 'Private Declare PtrSafe Function F Lib "kernel32" Alias "" () As Long\r\n', "Main = F()"),
    std("dec-empty-lib", 'Private Declare PtrSafe Function F Lib "" Alias "GetTickCount" () As Long\r\n', "Main = F()"),
    std("dec-lib-const", 'Private Const K As String = "kernel32"\r\nPrivate Declare PtrSafe Function F Lib K Alias "GetTickCount" () As Long\r\n', "Main = F()"),
    std("dec-dup-proc", TICK, "Main = 1", "Private Function GetTickCount() As Long\r\nEnd Function\r\n"),
    std("dec-dup-declare", TICK + TICK, "Main = 1"),
    std("dec-dup-var", TICK + "Private GetTickCount As Long\r\n", "Main = 1"),
    std("dec-dup-const", TICK + "Private Const GetTickCount As Long = 1\r\n", "Main = 1"),
    std("dec-name-builtin", 'Private Declare PtrSafe Function Len Lib "kernel32" Alias "GetTickCount" () As Long\r\n', "Main = Len() > 0"),
    std("dec-name-module", 'Private Declare PtrSafe Function Module1 Lib "kernel32" Alias "GetTickCount" () As Long\r\n', "Main = 1"),
    std("dec-name-keyword", 'Private Declare PtrSafe Function Print Lib "kernel32" Alias "GetTickCount" () As Long\r\n', "Main = 1"),
    two("dec-private-other-module", "", "Main = Tick2() > 0", 'Private Declare PtrSafe Function Tick2 Lib "kernel32" Alias "GetTickCount" () As Long\r\n'),
    two("dec-public-other-module", "", "Main = Tick2() > 0", 'Public Declare PtrSafe Function Tick2 Lib "kernel32" Alias "GetTickCount" () As Long\r\n'),
    two("dec-public-qualified", "", "Main = Module2.Tick2() > 0", 'Public Declare PtrSafe Function Tick2 Lib "kernel32" Alias "GetTickCount" () As Long\r\n'),
    std("dec-byref-long-to-longptr", 'Private Declare PtrSafe Sub F Lib "kernel32" Alias "Sleep" (p As LongPtr)\r\n', "Dim x As Long\nF x\nMain = 1"),
    std("dec-byref-int-to-long", 'Private Declare PtrSafe Sub F Lib "kernel32" Alias "Sleep" (p As Long)\r\n', "Dim x As Integer\nF x\nMain = 1"),
    std("dec-byval-string-overflow", SLEEP, "Sleep 3000000000#\nMain = 1"),
    std("dec-byval-type-mismatch", SLEEP, 'Sleep "abc"\nMain = 1'),
    std("dec-byval-long-overflow-lit", SLEEP, "Sleep 2147483648#\nMain = 1"),
    std("dec-call-keyword", SLEEP, "Call Sleep(0)\nMain = 1"),
    std("dec-in-proc", "", 'Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As Long\nMain = 1'),
    std("dec-no-ptrsafe-longptr", 'Private Declare Function F Lib "kernel32" Alias "GetTickCount" () As LongPtr\r\n', "Main = 1"),
    std("dec-as-any-return", 'Private Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As Any\r\n', "Main = 1"),
    std("dec-as-any-param-string", 'Private Declare PtrSafe Sub F Lib "kernel32" Alias "RtlZeroMemory" (d As Any, ByVal n As LongPtr)\r\n', "Dim x As Long\nx = 5\nF x, 4\nMain = x"),
    std("dec-addressof-nonproc", 'Private Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As Long\r\n', "Dim p As LongPtr\np = VarPtr(p)\nMain = 1"),
    std("dec-with-type-suffix", 'Private Declare PtrSafe Function F& Lib "kernel32" Alias "GetTickCount" ()\r\n', "Main = F() > 0"),
    std("dec-suffix-and-as", 'Private Declare PtrSafe Function F& Lib "kernel32" Alias "GetTickCount" () As Long\r\n', "Main = 1"),
    std("dec-sub-byval-nothing", 'Private Declare PtrSafe Sub F Lib "kernel32" Alias "Sleep" (ByVal ms As Long)\r\n', "F Nothing\nMain = 1"),
    std("dec-result-overflow", 'Private Declare PtrSafe Function F Lib "kernel32" Alias "GetTickCount" () As Long\r\n', "Dim b As Byte\nb = F()\nMain = 1"),

    # ---- Type (UDT) ----
    std("udt-ok", T, "Dim t As T\nt.a = 1\nMain = t.a"),
    std("udt-compare", T, "Dim t As T, t2 As T\nMain = (t = t2)"),
    std("udt-to-variant", T, "Dim t As T, v As Variant\nv = t\nMain = 1"),
    std("udt-to-main", T, "Dim t As T\nMain = t"),
    std("udt-concat", T, 'Dim t As T\nMain = "x" & t'),
    std("udt-debug-print", T, "Dim t As T\nDebug.Print t\nMain = 1"),
    std("udt-byval-variant-param", T + TS, "Dim t As T\nTakeV t\nMain = 1"),
    std("udt-collection-add", T, "Dim t As T, c As New Collection\nc.Add t\nMain = 1"),
    std("udt-array-fn", T, "Dim t As T, v As Variant\nv = Array(t)\nMain = 1"),
    std("udt-isempty", T, "Dim t As T\nMain = IsEmpty(t)"),
    std("udt-typename", T, "Dim t As T\nMain = TypeName(t)"),
    std("udt-vartype", T, "Dim t As T\nMain = VarType(t)"),
    std("udt-len", T, "Dim t As T\nMain = Len(t)"),
    std("udt-unknown-member", T, "Dim t As T\nMain = t.zz"),
    std("udt-unknown-member-write", T, "Dim t As T\nt.zz = 1\nMain = 1"),
    std("udt-assign-other-udt", T + U, "Dim t As T, u As U\nt = u\nMain = 1"),
    std("udt-lset-other-udt", T + U, "Dim t As T, u As U\nLSet t = u\nMain = 1"),
    std("udt-dyn-unalloc", T, "Dim t As T\nMain = t.d(0)"),
    std("udt-dyn-ubound-unalloc", T, "Dim t As T\nMain = UBound(t.d)"),
    std("udt-fixed-oob", T, "Dim t As T\nMain = t.f(3)"),
    std("udt-fixed-oob-write", T, "Dim t As T\nt.f(5) = 1\nMain = 1"),
    std("udt-fixed-ok", T, "Dim t As T\nt.f(2) = 4\nMain = t.f(2)"),
    std("udt-obj-nothing-call", T, "Dim t As T\nt.o.Add 1\nMain = 1"),
    std("udt-obj-nothing-read", T, "Dim t As T\nMain = t.o.Count"),
    std("udt-obj-let", T, "Dim t As T\nt.o = New Collection\nMain = 1"),
    std("udt-set-nonobject", T, "Dim t As T\nSet t.a = New Collection\nMain = 1"),
    std("udt-int-overflow", T, "Dim t As T\nt.i = 40000\nMain = 1"),
    std("udt-byte-overflow", T, "Dim t As T\nt.b = 256\nMain = 1"),
    std("udt-byte-neg", T, "Dim t As T\nt.b = -1\nMain = 1"),
    std("udt-long-string", T, 'Dim t As T\nt.a = "abc"\nMain = 1'),
    std("udt-date-string", T, 'Dim t As T\nt.dt = "notadate"\nMain = 1'),
    std("udt-int-arith-overflow", T, "Dim t As T\nt.i = 32767\nt.i = t.i + 1\nMain = 1"),
    std("udt-div-zero", T, "Dim t As T\nMain = 1 / t.a"),
    std("udt-intdiv-zero", T, "Dim t As T\nMain = 1 \\ t.i"),
    std("udt-set-whole", T, "Dim t As T\nSet t = MakeT()\nMain = 1", TS),
    std("udt-foreach-array", T, "Dim arr(1) As T, x As Variant\nFor Each x In arr\nNext\nMain = 1"),
    std("udt-foreach-udt-var", T, "Dim arr(1) As T, x As T\nFor Each x In arr\nNext\nMain = 1"),
    std("udt-erase", T, "Dim t As T\nErase t\nMain = 1"),
    std("udt-erase-member", T, "Dim t As T\nReDim t.d(3)\nErase t.d\nMain = UBound(t.d)"),
    std("udt-redim-member-ok", T, "Dim t As T\nReDim t.d(3)\nt.d(3) = 2\nMain = t.d(3)"),
    std("udt-redim-member-oob", T, "Dim t As T\nReDim t.d(3)\nMain = t.d(4)"),
    std("udt-redim-fixed-member", T, "Dim t As T\nReDim t.f(3)\nMain = 1"),
    std("udt-fn-member-write", T + TS, "MakeT().a = 5\nMain = 1"),
    std("udt-fn-member-read", T + TS, "Main = MakeT().a"),
    std("udt-with", T, "Dim t As T\nWith t\n.a = 3\n.f(1) = 2\nEnd With\nMain = t.a + t.f(1)"),
    std("udt-with-oob", T, "Dim t As T\nWith t\n.f(9) = 2\nEnd With\nMain = 1"),
    std("udt-array-oob", T, "Dim arr(2) As T\nMain = arr(3).a"),
    std("udt-array-member-oob", T, "Dim arr(2) As T\nMain = arr(1).f(7)"),
    std("udt-nested", "Private Type In1\r\n    v(1 To 2) As Integer\r\nEnd Type\r\nPrivate Type Out1\r\n    i As In1\r\nEnd Type\r\n", "Dim o As Out1\no.i.v(2) = 40000\nMain = 1"),
    std("udt-nested-oob", "Private Type In1\r\n    v(1 To 2) As Integer\r\nEnd Type\r\nPrivate Type Out1\r\n    i As In1\r\nEnd Type\r\n", "Dim o As Out1\no.i.v(3) = 1\nMain = 1"),
    std("udt-param-byref-fixed-oob", T + "Private Sub Poke(x As T)\r\n    x.f(3) = 1\r\nEnd Sub\r\n", "Dim t As T\nPoke t\nMain = 1"),
    std("udt-param-obj-nothing", T + "Private Function Cnt(x As T) As Long\r\n    Cnt = x.o.Count\r\nEnd Function\r\n", "Dim t As T\nMain = Cnt(t)"),
    std("udt-param-pass-variant", T + TS, "Dim v As Variant\nTakeT v\nMain = 1"),
    std("udt-param-pass-other", T + U + TS, "Dim u As U\nTakeT u\nMain = 1"),
    std("udt-member-is-nothing", T, "Dim t As T\nMain = t.o Is Nothing"),
    std("udt-string-member-mid", T, "Dim t As T\nMain = Mid$(t.s, 0, 1)"),
    std("udt-fixedstr-member", "Private Type F1\r\n    s As String * 3\r\nEnd Type\r\n", 'Dim f As F1\nf.s = "abcdef"\nMain = f.s'),
    std("udt-member-dot-call", T, "Dim t As T\nMain = t.a.Value"),
    std("udt-typed-date-overflow", T, "Dim t As T\nt.dt = #12/31/9999#\nt.dt = t.dt + 1\nMain = 1"),
    std("udt-member-cint", T, "Dim t As T\nt.a = 40000\nt.i = t.a\nMain = 1"),

    # ---- Const ----
    std("const-div-zero", "Private Const K = 1 / 0\r\n", "Main = K"),
    std("const-intdiv-zero", "Private Const K = 1 \\ 0\r\n", "Main = K"),
    std("const-mod-zero", "Private Const K = 1 Mod 0\r\n", "Main = K"),
    std("const-pow-overflow", "Private Const K = 10 ^ 400\r\n", "Main = K"),
    std("const-pow-ok", "Private Const K = 2 ^ 10\r\n", "Main = K"),
    std("const-single-overflow", "Private Const K As Single = 1E+39\r\n", "Main = K"),
    std("const-double-mult-overflow", "Private Const K = 1E+308 * 10\r\n", "Main = K"),
    std("const-byte-sum-overflow", "Private Const K As Byte = 255 + 1\r\n", "Main = K"),
    std("const-long-string", 'Private Const K As Long = "abc"\r\n', "Main = K"),
    std("const-long-numstring", 'Private Const K As Long = "12"\r\n', "Main = K"),
    std("const-int-float", "Private Const K As Integer = 2.5\r\n", "Main = K"),
    std("const-date-string", 'Private Const K As Date = "abc"\r\n', "Main = K"),
    std("const-bool-string", 'Private Const K As Boolean = "abc"\r\n', "Main = K"),
    std("const-fn-len", 'Private Const K = Len("abc")\r\n', "Main = K"),
    std("const-fn-chr", "Private Const K = Chr(65)\r\n", "Main = K"),
    std("const-fn-chrw", "Private Const K = ChrW(65)\r\n", "Main = K"),
    std("const-fn-abs", "Private Const K = Abs(-1)\r\n", "Main = K"),
    std("const-fn-int", "Private Const K = Int(1.5)\r\n", "Main = K"),
    std("const-fn-sgn", "Private Const K = Sgn(-1)\r\n", "Main = K"),
    std("const-fn-cint", "Private Const K = CInt(1)\r\n", "Main = K"),
    std("const-fn-asc", 'Private Const K = Asc("A")\r\n', "Main = K"),
    std("const-fn-lenb", 'Private Const K = LenB("a")\r\n', "Main = K"),
    std("const-fn-now", "Private Const K = Now\r\n", "Main = K"),
    std("const-fn-rgb", "Private Const K = RGB(1, 2, 3)\r\n", "Main = K"),
    std("const-fn-fix", "Private Const K = Fix(1.5)\r\n", "Main = K"),
    std("const-fn-vbcrlf", "Private Const K = vbCrLf & \"a\"\r\n", "Main = K"),
    std("const-fn-len-const", 'Private Const A1 = "abc"\r\nPrivate Const K = Len(A1)\r\n', "Main = K"),
    std("const-fn-len-var", "Private v As String\r\nPrivate Const K = Len(v)\r\n", "Main = K"),
    std("const-from-var", "Private v As Long\r\nPrivate Const K = v\r\n", "Main = K"),
    std("const-object", "Private Const K As Object = Nothing\r\n", "Main = 1"),
    std("const-variant-empty", "Private Const K As Variant = Empty\r\n", "Main = IsEmpty(K)"),
    std("const-null", "Private Const K = Null\r\n", "Main = IsNull(K)"),
    std("const-bool-plus", "Private Const K = True + 1\r\n", "Main = K"),
    std("const-like", 'Private Const K = "a" Like "a"\r\n', "Main = K"),
    std("const-is", "Private Const K = Nothing Is Nothing\r\n", "Main = K"),
    std("const-array", "Private Const K = Array(1)\r\n", "Main = 1"),
    std("const-fixedstr", 'Private Const K As String * 5 = "abc"\r\n', "Main = K"),
    std("const-suffix-mismatch", 'Private Const K% = "x"\r\n', "Main = K"),
    std("const-suffix-overflow", "Private Const K% = 40000\r\n", "Main = K"),
    std("const-suffix-long-overflow", "Private Const K& = 3000000000#\r\n", "Main = K"),
    std("const-suffix-and-as", "Private Const K% As Integer = 1\r\n", "Main = K"),
    std("const-suffix-as-conflict", "Private Const K% As Long = 1\r\n", "Main = K"),
    std("const-hex-int", "Private Const K As Integer = &H8000\r\n", "Main = K"),
    std("const-hex-long-to-int", "Private Const K As Integer = &H8000&\r\n", "Main = K"),
    std("const-assign", "Private Const K = 1\r\n", "K = 2\nMain = K"),
    std("const-assign-local", "", "Const K = 1\nK = 2\nMain = K"),
    std("const-for-counter", "Private Const K = 1\r\n", "For K = 1 To 3\nNext\nMain = 1"),
    std("const-redim", "Private Const K = 1\r\n", "ReDim K(3)\nMain = 1"),
    std("const-set", "Private Const K = 1\r\n", "Set K = Nothing\nMain = 1"),
    std("const-byref-pass", "Private Const K = 1\r\n", "Bump K\nMain = K", "Private Sub Bump(x As Variant)\r\n    x = x + 1\r\nEnd Sub\r\n"),
    std("const-input-target", "Private Const K = 1\r\n", "Mid(K, 1, 1) = \"x\"\nMain = K"),
    std("const-rt-overflow", "Private Const K As Long = 2147483647\r\n", "Dim x As Long\nx = K + 1\nMain = x"),
    std("const-rt-overflow-int", "Private Const K As Integer = 32767\r\n", "Dim x As Integer\nx = K\nx = x + 1\nMain = x"),
    std("const-rt-div", "Private Const K = 0\r\n", "Dim x As Double\nx = 1 / K\nMain = x"),
    std("const-rt-array-oob", "Private Const K = 5\r\n", "Dim a(3) As Long\na(K) = 1\nMain = 1"),
    std("const-rt-array-oob-typed", "Private Const K As Long = 5\r\n", "Dim a(3) As Long\nMain = a(K)"),
    std("const-rt-array-bound-neg", "Private Const K = -1\r\n", "Dim a() As Long\nReDim a(K)\nMain = 1"),
    std("const-rt-string-to-long", 'Private Const K = "abc"\r\n', "Dim x As Long\nx = K\nMain = x"),
    std("const-rt-string-to-int-overflow", 'Private Const K = "40000"\r\n', "Dim x As Integer\nx = K\nMain = x"),
    std("const-rt-mid-zero", "Private Const K = 0\r\n", 'Main = Mid$("abc", K, 1)'),
    std("const-rt-left-neg", "Private Const K = -1\r\n", 'Main = Left$("abc", K)'),
    std("const-rt-chr-bad", "Private Const K = 300\r\n", "Main = Chr$(K)"),
    std("const-rt-space-neg", "Private Const K = -2\r\n", "Main = Space$(K)"),
    std("const-rt-cint", "Private Const K = 40000\r\n", "Main = CInt(K)"),
    std("const-rt-cbyte", "Private Const K = -1\r\n", "Main = CByte(K)"),
    std("const-rt-sqr", "Private Const K = -4\r\n", "Main = Sqr(K)"),
    std("const-rt-log", "Private Const K = 0\r\n", "Main = Log(K)"),
    std("const-rt-dateserial", "Private Const K = 99999\r\n", "Main = DateSerial(K, 1, 1)"),
    std("const-rt-string-neg", "Private Const K = -1\r\n", 'Main = String$(K, "a")'),
    std("const-rt-collection-index", "Private Const K = 3\r\n", "Dim c As New Collection\nc.Add 1\nMain = c(K)"),
    std("const-rt-step-zero", "Private Const K = 0\r\n", "Dim i As Long, n As Long\nFor i = 1 To 3 Step K\nn = n + 1\nIf n > 5 Then Exit For\nNext\nMain = n"),
    std("const-rt-err-raise", "Private Const K = 0\r\n", "Err.Raise K\nMain = 1"),
    std("const-rt-error-stmt", "Private Const K = 70000\r\n", "Error K\nMain = 1"),
    std("const-rt-enum-overflow", "Private Enum E\r\n    eBig = 2147483647\r\nEnd Enum\r\n", "Dim x As Long\nx = eBig + 1\nMain = x"),
    std("const-rt-enum-int", "Private Enum E\r\n    eBig = 40000\r\nEnd Enum\r\n", "Dim x As Integer\nx = eBig\nMain = x"),
    std("const-local-shadows", "Private Const K = 1\r\n", "Const K = 2\nMain = K"),
    std("const-local-dup", "", "Const K = 1\nConst K = 2\nMain = K"),
    std("const-local-dup-var", "", "Dim K As Long\nConst K = 2\nMain = K"),
    std("const-dup-module", "Private Const K = 1\r\nPrivate Const K = 2\r\n", "Main = K"),
    std("const-dup-module-var", "Private Const K = 1\r\nPrivate K As Long\r\n", "Main = K"),
    std("const-name-proc", "Private Const Foo = 1\r\n", "Main = Foo", "Private Sub Foo()\r\nEnd Sub\r\n"),
    std("const-multi-line", "Private Const A1 = 1, B1 As Long = 2, C1 = A1 + B1\r\n", "Main = C1"),
    std("const-typed-then-untyped-ref", "Private Const A1 As Byte = 200\r\nPrivate Const B1 = A1 + A1\r\n", "Main = B1"),
    std("const-byte-plus-byte-overflow", "Private Const A1 As Byte = 200\r\nPrivate Const B1 As Byte = 100\r\nPrivate Const C1 = A1 + B1\r\n", "Main = C1"),
    std("const-int-mult-overflow", "Private Const A1 As Integer = 300\r\nPrivate Const C1 = A1 * A1\r\n", "Main = C1"),
    std("const-int-mult-overflow-rt", "Private Const A1 As Integer = 300\r\n", "Main = A1 * A1"),
    std("const-date-add", "Private Const D1 As Date = #12/31/9999#\r\nPrivate Const D2 = D1 + 1\r\n", "Main = D2"),
    std("const-string-minus", 'Private Const K = "a" - 1\r\n', "Main = K"),
    std("const-string-numeric-minus", 'Private Const K = "5" - 1\r\n', "Main = K"),
    std("const-string-plus-num", 'Private Const K = "a" + 1\r\n', "Main = K"),
    std("const-not-string", 'Private Const K = Not "a"\r\n', "Main = K"),
    std("const-neg-string", 'Private Const K = -"a"\r\n', "Main = K"),
    std("const-cstr-overflow-in", 'Private Const K As Integer = "40000"\r\n', "Main = K"),
    std("const-enum-typed-overflow", "Private Enum E\r\n    eBig = 40000\r\nEnd Enum\r\nPrivate Const K As Integer = eBig\r\n", "Main = K"),
    std("const-public-in-proc", "", "Public Const K = 1\nMain = K"),
    std("const-static", "", "Static Const K = 1\nMain = K"),
]

if __name__ == "__main__":
    json.dump(CASES, open(sys.argv[1], "w", encoding="utf-8"), indent=1)
    print(len(CASES), "cases")
