"""The diagnostic rule catalogue (115 rules), loaded from vendored data.

Ported from the data in xlide_vscode/src/analyzer/diagnostics/ruleMetadata.ts.
The 1500-line TypeScript object literal is vendored verbatim as
pyvbaanalysis/data/rule_metadata.json (generated by evaluating DIAGNOSTIC_RULES;
see the data-package manifest) and loaded into dataclasses here, per the agent.md
seam: Python consumes the rule metadata as data rather than hand-porting it.

The catalogue holds 115 rules; the two structural block-balance codes
(missing-block-closer, unmatched-block-closer) are emitted by the parser pass, not
this rule catalogue, so the full audited set is 117.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from ..evidence import DATA_DIR
from .model import (
    DiagnosticCategory,
    DiagnosticEvidenceKind,
    DiagnosticSeverity,
    DiagnosticSuppressionScope,
)

DEFAULT_DIAGNOSTIC_SUPPRESSION_SCOPES: tuple[DiagnosticSuppressionScope, ...] = (
    DiagnosticSuppressionScope.BLOCK,
    DiagnosticSuppressionScope.MEMBER,
    DiagnosticSuppressionScope.MODULE,
)


@dataclass(frozen=True, slots=True)
class DiagnosticRuleMetadata:
    """Static description of a single diagnostic rule."""

    # Stable rule name (the DIAGNOSTIC_RULES key, e.g. "unterminatedString").
    rule_name: str
    # Stable identifier shown as the diagnostic code (e.g. "unterminated-string").
    code: str
    title: str
    default_severity: DiagnosticSeverity
    category: DiagnosticCategory
    vbe_compile_equivalent: bool
    diagnostic_kind: DiagnosticEvidenceKind
    source: str  # always "XLIDE"
    confidence: str  # "high" | "medium" | "low"
    spec_reference: str | None = None
    requires_whole_project: bool | None = None
    suppression_scopes: tuple[DiagnosticSuppressionScope, ...] | None = None
    allow_severity_downgrade: bool | None = None


def _build(rule_name: str, raw: dict[str, Any]) -> DiagnosticRuleMetadata:
    scopes_raw = raw.get("suppressionScopes")
    return DiagnosticRuleMetadata(
        rule_name=rule_name,
        code=raw["code"],
        title=raw["title"],
        default_severity=DiagnosticSeverity(raw["defaultSeverity"]),
        category=DiagnosticCategory(raw["category"]),
        vbe_compile_equivalent=raw["vbeCompileEquivalent"],
        diagnostic_kind=DiagnosticEvidenceKind(raw["diagnosticKind"]),
        source=raw["source"],
        confidence=raw["confidence"],
        spec_reference=raw.get("specReference"),
        requires_whole_project=raw.get("requiresWholeProject"),
        suppression_scopes=(
            tuple(DiagnosticSuppressionScope(s) for s in scopes_raw) if scopes_raw is not None else None
        ),
        allow_severity_downgrade=raw.get("allowSeverityDowngrade"),
    )


def load_rule_metadata() -> dict[str, DiagnosticRuleMetadata]:
    """Load the rule catalogue keyed by stable rule name."""
    doc: dict[str, Any] = json.loads((DATA_DIR / "rule_metadata.json").read_text(encoding="utf-8"))
    return {name: _build(name, raw) for name, raw in doc.items()}


# Loaded once at import; the vendored catalogue is small and always present.
DIAGNOSTIC_RULES: dict[str, DiagnosticRuleMetadata] = load_rule_metadata()


def rule_metadata_by_code() -> dict[str, DiagnosticRuleMetadata]:
    """The rule catalogue keyed by diagnostic code instead of rule name."""
    return {meta.code: meta for meta in DIAGNOSTIC_RULES.values()}


__all__ = [
    "DiagnosticRuleMetadata",
    "DIAGNOSTIC_RULES",
    "DEFAULT_DIAGNOSTIC_SUPPRESSION_SCOPES",
    "load_rule_metadata",
    "rule_metadata_by_code",
]
