"""Loaders for the vendored XLIDE evidence corpus.

The oracle case corpus and the diagnostic provenance audit are owned and
generated by XLIDE and vendored under pyvbaanalysis/data/ (see agent.md). They are
the porting spec and the test fixtures. Do not hand-edit the vendored JSON.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).parent / "data"


@dataclass(frozen=True, slots=True)
class OracleModule:
    """One VBA module within an oracle case (name, kind, source text)."""

    name: str
    module_type: str
    source: str


@dataclass(frozen=True, slots=True)
class OracleCase:
    """One Excel/VBE-verified case. `expected` is rejected / accepted / observe;
    `mode` is compile / run / compile_then_run. A case is one or more modules:
    single-module cases carry a `source`, multi-module cases a `modules` list; both
    are normalized to `modules` here."""

    id: str
    description: str
    provenance: str
    expected: str
    mode: str
    modules: tuple[OracleModule, ...]
    entry_point: str | None = None
    evidence_phase: str | None = None
    diagnostic_meaning: str | None = None

    @property
    def sources(self) -> tuple[str, ...]:
        """Every module's source text."""
        return tuple(m.source for m in self.modules)


@dataclass(frozen=True, slots=True)
class AuditEntry:
    """One audited diagnostic code and the oracle cases that back it."""

    code: str
    status: str
    diagnostic_kind: str
    asserted_oracle_cases: tuple[str, ...]


def _load_json(name: str) -> dict[str, Any]:
    data: dict[str, Any] = json.loads((DATA_DIR / name).read_text(encoding="utf-8"))
    return data


def _case_modules(c: dict[str, Any]) -> tuple[OracleModule, ...]:
    if "modules" in c:
        return tuple(
            OracleModule(name=m["name"], module_type=m.get("type", "standard"), source=m["source"])
            for m in c["modules"]
        )
    return (
        OracleModule(name=c.get("moduleName", "Module1"), module_type="standard", source=c["source"]),
    )


def load_oracle_cases() -> list[OracleCase]:
    """Load every vendored Excel/VBE oracle case (single- and multi-module)."""
    doc = _load_json("vbe_oracle_cases.json")
    return [
        OracleCase(
            id=c["id"],
            description=c.get("description", ""),
            provenance=c.get("provenance", ""),
            expected=c["expected"],
            mode=c.get("mode", "compile"),
            modules=_case_modules(c),
            entry_point=c.get("entryPoint"),
            evidence_phase=c.get("evidencePhase"),
            diagnostic_meaning=c.get("diagnosticMeaning"),
        )
        for c in doc["cases"]
    ]


def load_audit() -> list[AuditEntry]:
    """Load the diagnostic provenance audit (the shipped code set)."""
    doc = _load_json("diagnostic_influence_audit.json")
    return [
        AuditEntry(
            code=d["code"],
            status=d["status"],
            diagnostic_kind=d.get("diagnosticKind", ""),
            asserted_oracle_cases=tuple(d.get("assertedOracleCases", ())),
        )
        for d in doc["diagnostics"]
    ]


def load_manifest() -> dict[str, Any]:
    """Load the data-package manifest (version, checksums, counts, code list)."""
    return _load_json("manifest.json")
